"""Separate reading and audio-first listening observations for frozen questions.

The source, question and bounded expected meaning are frozen together. Existing
reading contracts never become listening evidence. Written answers demonstrate
comprehension; they are not a writing exam or a proficiency gate.
"""
from copy import deepcopy
import hashlib
import json
from pathlib import Path
import re

from contracts.curriculum import CONTRACT_VERSION, freeze_task_contract, validate_task_contract
from services.curriculum import normalize_level
from services.torfl_requirements import VERSION, reference_for_level
from services.vocabulary_topics import TOPICS
from utils.story_content import validate_reading_focus

CONTENT_VERSION = 'comprehension-reading-v1'
RUBRIC_VERSION = 'comprehension-reading-focus-v1'
QUESTION_INDEXES = ('0', '1', '2', '3')
SUPPORT_VERSION = 'comprehension-support-v1'
LISTENING_CONTENT_VERSION = 'comprehension-listening-v1'
LISTENING_RUBRIC_VERSION = 'comprehension-listening-focus-v1'


def reading_candidates(difficulty):
    level = normalize_level(difficulty, legacy='reading')
    reference = reference_for_level(level)
    return {item['id']: item for item in reference['requirements']
            if item['domain'] == 'reading'} if reference else {}


def listening_candidates(difficulty):
    level = normalize_level(difficulty, legacy='reading')
    reference = reference_for_level(level)
    return {item['id']: item for item in reference['requirements']
            if item['domain'] == 'listening'} if reference else {}


def validate_audio(audio):
    """Check a generated recording's frozen identity without accessing files."""
    if audio is None:
        return None
    if (not isinstance(audio, dict) or set(audio) != {'url', 'sha256', 'size_bytes'}
            or not isinstance(audio['url'], str)
            or not re.fullmatch(r'/static/media/[A-Za-z0-9][A-Za-z0-9_.-]{0,199}\.mp3', audio['url'])
            or not isinstance(audio['sha256'], str) or not re.fullmatch(r'[a-f0-9]{64}', audio['sha256'])
            or type(audio['size_bytes']) is not int or not 0 < audio['size_bytes'] <= 50_000_000):
        raise ValueError('The listening task needs its original recording identity.')
    return audio


def _media_root(media_root=None):
    if media_root is None:
        from flask import current_app, has_app_context
        media_root = current_app.config['APP_MEDIA_DIR'] if has_app_context() else Path(__file__).resolve().parents[1] / 'static' / 'media'
    return Path(media_root).resolve()


def freeze_audio(audio_url, media_root=None):
    """Bind the exact generated bytes once; unavailable audio stays unavailable."""
    if not audio_url:
        return None
    if not isinstance(audio_url, str) or not re.fullmatch(r'/static/media/[A-Za-z0-9][A-Za-z0-9_.-]{0,199}\.mp3', audio_url):
        raise ValueError('Use generated local audio for a listening task.')
    root = _media_root(media_root)
    path = root / audio_url.removeprefix('/static/media/')
    try:
        if not path.is_file() or not path.resolve().is_relative_to(root) or not 0 < path.stat().st_size <= 50_000_000:
            return None
        data = path.read_bytes()
    except OSError:
        return None
    if not 0 < len(data) <= 50_000_000:
        return None
    return {'url': audio_url, 'sha256': hashlib.sha256(data).hexdigest(), 'size_bytes': len(data)}


def verify_audio(audio, media_root=None):
    validate_audio(audio)
    if audio is None:
        raise ValueError('This recording is unavailable. You can read the transcript instead.')
    current = freeze_audio(audio['url'], media_root)
    if current != audio:
        raise ValueError('This recording is unavailable. You can read the transcript instead.')
    return _media_root(media_root) / audio['url'].removeprefix('/static/media/')


def build_contracts(prepared, topic, difficulty, *, practice_mode='reading', audio=None, track_support=False):
    """Freeze the original four passage questions; reflection stays unmapped."""
    level = normalize_level(difficulty, legacy='reading')
    if practice_mode not in ('reading', 'listening'):
        raise ValueError('Choose reading or listening practice.')
    listening = practice_mode == 'listening'
    candidates = listening_candidates(level) if listening else reading_candidates(level)
    if not candidates:
        return {}
    if topic != 'any' and topic not in TOPICS:
        raise ValueError('Use a canonical comprehension topic.')
    if not isinstance(prepared, dict):
        raise ValueError('Comprehension requires its saved passage and questions.')
    text, questions = prepared.get('text'), prepared.get('questions')
    if (not isinstance(text, str) or not text.strip() or len(text) > 100_000 or '\x00' in text
            or not isinstance(questions, list) or not 5 <= len(questions) <= 20
            or any(not isinstance(q, str) or not q.strip() or len(q) > 2000 or '\x00' in q for q in questions)
            or len(questions) != len(set(questions))):
        raise ValueError('Use a complete passage and five to twenty distinct questions.')
    focus_key = 'listening_focus' if listening else 'reading_focus'
    focus_data = {**prepared, 'reading_focus': prepared.get(focus_key)}
    validate_reading_focus(focus_data, candidates, TOPICS if topic == 'any' else (topic,), text)
    if listening:
        validate_audio(audio)
    content_version = LISTENING_CONTENT_VERSION if listening else 'comprehension-reading-support-v1' if track_support else CONTENT_VERSION
    allowed = ['translation', 'model_answer']
    if listening or track_support:
        allowed.append('hint')
    if listening:
        allowed.append('transcript')
    contracts = {}
    for focus in sorted(prepared[focus_key], key=lambda item: item['question_index']):
        index, rid = focus['question_index'], focus['requirement_id']
        content = {'text': text, 'questions': deepcopy(questions), 'question_index': index,
                   focus_key: deepcopy(focus), 'requested_topic': topic, 'topic_id': prepared['topic_id']}
        if listening:
            content['audio'] = deepcopy(audio)
        identity = hashlib.sha256(json.dumps({'content': content, 'level': level, 'version': content_version},
                                            ensure_ascii=False, sort_keys=True, separators=(',', ':')).encode()).hexdigest()
        contracts[str(index)] = freeze_task_contract({
            'schema_version': 1, 'contract_version': CONTRACT_VERSION, 'reference_version': VERSION,
            'task_id': f'comprehension-{practice_mode}-{identity}', 'activity': 'comprehension',
            'content_version': content_version, 'level': level, 'topic_ids': [prepared['topic_id']],
            'purpose': 'diagnostic', 'content': content, 'rubric_version': LISTENING_RUBRIC_VERSION if listening else RUBRIC_VERSION,
            'support': {'allowed': allowed.copy(), 'independence_breakers': allowed.copy()},
            'criteria': [{'id': f'{practice_mode}-focus', 'target_id': f'comprehension-{practice_mode}.{rid}',
                          'requirement_id': rid, 'response_mode': f'{practice_mode}_response',
                          'evidence_scope': f'{practice_mode}_comprehension', 'expectation': focus['expectation'],
                          'max_score': 2, 'source_refs': candidates[rid]['source_refs']}],
        })
    return contracts


def validate_contracts(task):
    """Bind each contract to the full saved task, including extra questions."""
    contracts = task.get('contracts')
    if not isinstance(contracts, dict) or set(contracts) != set(QUESTION_INDEXES):
        raise ValueError('A comprehension task needs its four original comprehension contracts.')
    for contract in contracts.values():
        validate_task_contract(contract)
    first = contracts['0']['content']
    mode = task.get('practice_mode', 'reading')
    focus_key = 'listening_focus' if mode == 'listening' else 'reading_focus'
    prepared = {'text': task['text'], 'questions': task['questions'],
                'topic_id': first.get('topic_id'),
                focus_key: [contracts[key]['content'].get(focus_key) for key in QUESTION_INDEXES]}
    if mode == 'listening' and ('audio' not in task or task.get('support_version') != SUPPORT_VERSION):
        raise ValueError('Listening requires its frozen audio and support policy.')
    expected = build_contracts(prepared, task['topic'], task['difficulty'], practice_mode=mode, audio=task.get('audio'),
                               track_support=task.get('support_version') == SUPPORT_VERSION)
    if not expected or contracts != expected:
        raise ValueError('Comprehension contracts do not match the saved passage, questions or focus.')
    return deepcopy(contracts)


def reissue_contracts(task, new_questions):
    """Additional questions get a new task identity without new criterion claims."""
    contracts = validate_contracts(task)
    if not isinstance(new_questions, list) or new_questions[:4] != task['questions'][:4]:
        raise ValueError('The four original comprehension questions cannot change their saved focus.')
    mode = task.get('practice_mode', 'reading')
    focus_key = 'listening_focus' if mode == 'listening' else 'reading_focus'
    prepared = {'text': task['text'], 'questions': new_questions,
                'topic_id': contracts['0']['content']['topic_id'],
                focus_key: [contracts[key]['content'][focus_key] for key in QUESTION_INDEXES]}
    return build_contracts(prepared, task['topic'], task['difficulty'], practice_mode=mode, audio=task.get('audio'),
                           track_support=task.get('support_version') == SUPPORT_VERSION)
