export type DeliveryNode={id:string;x:number;y:number;label:string;label_en:string;kind:string;building_side?:string;building_id?:string;entrance?:boolean|string};
export type DeliverySpeaker={name:string;name_en:string;role:string;role_en:string;portrait:string};
export type DeliveryLine={id:string;text?:string;english?:string;audio_url:string};
export type DeliveryFrontage='n'|'e'|'s'|'w';
export type DeliveryTile={x:number;y:number;kind:string;exits?:DeliveryFrontage[];building_kind?:string;building_id?:string;colour?:string;label?:string;label_en?:string;frontage?:DeliveryFrontage;decorative?:boolean};
export type DeliveryStreet={from:string;to:string;kind:'main'|'residential'|'path'};
export type DeliveryBlock={id:string;x:number;y:number;width:number;height:number;kind:'residential'|'market'|'park'|'courtyard'|'civic'};
export type DeliveryPlot={id:string;building_id?:string;x:number;y:number;width:number;height:number;kind:'garden'|'paved'|'lawn';frontage?:DeliveryFrontage};
export type DeliveryMapData={nodes:DeliveryNode[];edges:string[][];name_ru?:string;name_en?:string;scene?:string;width?:number;height?:number;tile_size?:number;tiles?:DeliveryTile[];street_segments?:DeliveryStreet[];blocks?:DeliveryBlock[];plots?:DeliveryPlot[];districts?:{id:string;name:string;name_ru:string;x:number;y:number;width:number;height:number}[];closures?:{node_id:string;reason:string;reason_ru:string}[]};
export type DeliveryTransport={id:string;label:string;label_ru:string;board:string;status:'waiting'|'aboard'|'arrived';stop_id?:string;visited?:string[];stops:{id:string;label:string;label_ru:string}[]};
export type DeliveryState={revision:number;phase:'dialogue'|'planning'|'feedback'|'arrived'|'completed';leg:number;title_ru:string;
  envelope:string;map:DeliveryMapData;position:string;heading:string;draft:string[];walked?:string[];last_path:string[];
  objective:string;objective_ru:string;speaker:DeliverySpeaker;arrival_speaker:DeliverySpeaker;lines:DeliveryLine[];
  support:Record<string,string|boolean>;feedback:null|{correct:boolean;code:string;en:string;ru:string;assisted?:boolean;navigation?:boolean;checks?:{id:string;label:string;label_ru:string;complete:boolean}[]};
  notebook:{speaker:DeliverySpeaker;lines:DeliveryLine[]}[];glossary:{form:string;lemma:string}[];
  encounters?:{position:string;speaker:DeliverySpeaker}[];
  questions?:{id:string;text:string;text_en:string;reply?:DeliveryLine}[];question_required?:boolean;
  inventory?:{id:string;label:string;label_ru:string}[];interaction?:'guide';transport?:DeliveryTransport;transport_leg?:boolean;
  arrival_text?:string;arrival_text_ru?:string;arrival_action_label?:string;arrival_action_label_ru?:string;completion_text?:string;completion_text_ru?:string;
  clarification?:DeliveryLine;guided_path?:string[];ending?:DeliveryLine;
  word?:{form:string;lemma:string;sentence:string;translation:string;target_meaning:string};
  mode?:'reading'|'listening';heard?:string[];can_go?:boolean;text_visible?:boolean;reviewing?:boolean;clarify_prompt?:string;
  stages?:{name:string;name_ru:string;title:string;title_ru:string}[];
  practice_sections?:{leg:number;title:string;title_ru:string;needs_practice:boolean}[];
  first_checks:{leg:number;correct:boolean;assisted:boolean;presentation?:string}[]};
