/* Interface copy only. Russian exercises and English contextual cues stay intact. */
export const gameRussian: Record<string, string> = {
  "In the shop": "В магазине",
  "Unlock this game in the shop with Lingocoins.": "Откройте эту игру в магазине за лингокоины.",
  "Visit the shop": "В магазин",
  "Use your Lingocoins to choose new games from the shop.": "Открывайте новые игры за лингокоины в магазине.",
  "Choose your next game. Unlock it once and keep playing.": "Выберите следующую игру. Откройте её один раз и играйте когда захотите.",
  "More games": "Другие игры",
  "Shop": "Магазин",
  "Unlock a game with Lingocoins. It’s yours to play whenever you like.": "Откройте игру за лингокоины и играйте когда захотите.",
  "Your balance": "Ваш баланс",
  "Balance unavailable": "Баланс недоступен",
  "{0} Lingocoins": "{0} лингокоинов",
  "Your first game costs 25 Lingocoins. Each game after that costs 50.": "Первая игра стоит 25 лингокоинов. Каждая следующая — 50.",
  "Earn coins through practice": "Зарабатывайте монеты за занятия",
  "Barsik sitting at his little shop, ready to welcome you.": "Барсик сидит у своего маленького магазина и ждёт вас.",
  "{0} is yours. You can play it whenever you like.": "«{0}» открыта. Играйте когда захотите.",
  "The shop could not load. Please try again.": "Не удалось загрузить магазин. Попробуйте ещё раз.",
  "Refresh shop": "Обновить магазин",
  "to save your games and use your Lingocoins.": "для сохранения игр и покупок за лингокоины.",
  "Try the sample games here. The shop is available in your own installation.": "Здесь можно попробовать примеры игр. Магазин доступен в собственной установке.",
  "Opening the shop…": "Открываем магазин…",
  "Play {0}": "Играть: {0}",
  "Yours to play": "Ваша игра",
  "Unlock {0} for {1} Lingocoins": "Открыть «{0}» за {1} лингокоинов",
  "Unlocking…": "Открываем…",
  "Unlock for": "Открыть за",
  "{0} more coins needed": "Нужно ещё {0} монет",
  "Choose a profile to unlock games.": "Выберите профиль, чтобы открывать игры.",

  "Preparing your delivery.": "Готовим доставку.",
  "Writing the conversation.": "Готовим разговор.",
  "Checking the conversation.": "Проверяем разговор.",
  "Preparing the voices.": "Готовим озвучку.",
  "Your delivery is ready.": "Доставка готова.",
  "A game with Barsik": "Игра с Барсиком",
  "A little more familiar.": "Слова стали знакомее.",
  "A reply for Barsik.": "Ответ Барсику.",
  "A short programme with familiar language and a few new words.": "Короткая передача со знакомыми и несколькими новыми словами.",
  "About a minute · 4 questions": "Около минуты · 4 вопроса",
  "Activities": "Занятия",
  "Add to my words": "Добавить в мои слова",
  "Add words to": "Добавьте слова в",
  "Added to your balance": "Добавлено на ваш счёт",
  "Added to your vocabulary.": "Добавлено в ваш словарь.",
  "All activities": "Все занятия",
  "Already in your vocabulary.": "Уже есть в вашем словаре.",
  "Already saved": "Уже сохранено",
  "An authored sample. Full vocabulary practice is available in your own installation.": "Готовый пример. Занятия с вашим словарём доступны в собственной установке.",
  "Answer choices": "Варианты ответа",
  "Answer the questions": "Ответить на вопросы",
  "Any difficulty": "Любая сложность",
  "Any topic": "Любая тема",
  "Available in your own installation.": "Доступно в собственной установке.",
  "Back to First steps": "К первым шагам",
  "Back to the lesson": "К уроку",
  "Back to vocabulary": "К словарю",
  "Barsik is facing": "Барсик смотрит",
  "Barsik’s bag": "Сумка Барсика",
  "Belongs here": "Подходящие сообщения",
  "Both clues fit.": "Обе подсказки подходят.",
  "Build on familiar words": "Знакомые слова",
  "Build on my vocabulary": "Использовать мой словарь",
  "Build on words you know, meet new ones and try a different way to practise.": "Повторяйте знакомые слова, узнавайте новые и пробуйте разные занятия.",
  "Case closed.": "Дело раскрыто.",
  "Check answer": "Проверить ответ",
  "Check the bag": "Проверить сумку",
  "Check the clues": "Проверить подсказки",
  "Check the mail": "Проверить почту",
  "Check the message": "Проверить сообщение",
  "Check the pairs": "Проверить пары",
  "Check the postcard": "Проверить открытку",
  "Check the route": "Проверить маршрут",
  "Check what I heard": "Проверить ответ",
  "Choose a Russian card, then its picture. You can change your pairs before checking.": "Выберите русскую открытку, затем картинку. До проверки пары можно менять.",
  "Choose a Russian postcard, then its matching picture. Pair all the cards before checking.": "Выберите русскую открытку и подходящую картинку. Перед проверкой составьте все пары.",
  "Choose a message, then a mailbox. You can move it again before checking.": "Выберите сообщение и почтовый ящик. До проверки сообщение можно переместить.",
  "Choose a picture": "Выберите картинку",
  "Choose a tile below to start your message.": "Выберите слово внизу, чтобы начать сообщение.",
  "Choose another activity": "Выбрать другое занятие",
  "Choose pictures to pack. Click a packed picture to put it back.": "Выберите картинки для сумки. Нажмите на выбранную картинку, чтобы вернуть её.",
  "Choose the answer that matches the programme.": "Выберите ответ по содержанию передачи.",
  "Choose words": "Выбрать слова",
  "Choose your profile": "Выбрать профиль",
  "Close": "Закрыть",
  "Close review": "Закрыть повторение",
  "Coming up": "Впереди",
  "Coming up ·": "Впереди ·",
  "Complete the postcard": "Дополните открытку",
  "Continue": "Продолжить",
  "Continue playing": "Продолжить игру",
  "Continue saved game": "Продолжить сохранённую игру",
  "Correct": "Верно",
  "Correct answer": "Правильный ответ",
  "Correct item": "Правильный предмет",
  "Create a profile to keep it.": "Создайте профиль, чтобы сохранить результат.",
  "Customise the programme": "Настроить передачу",
  "Different item needed": "Нужен другой предмет",
  "Difficulty": "Сложность",
  "Vocabulary difficulty": "Сложность слов",
  "Every message has a place.": "Все сообщения на своих местах.",
  "Explore and practise": "Изучайте и практикуйтесь",
  "Finish": "Завершить",
  "Finish game": "Завершить игру",
  "Finish programme": "Завершить передачу",
  "Form in this activity:": "Форма в этом задании:",
  "Game complete": "Игра завершена",
  "Game length": "Длина игры",
  "Game preparation": "Подготовка игры",
  "Games along the way": "Игры в пути",
  "Games from this lesson": "Игры из этого урока",
  "Games to discover": "Новые игры",
  "Getting ready to play.": "Готовимся к игре.",
  "Getting your game ready": "Подготовка игры",
  "Go straight": "Идти прямо",
  "Just what Barsik needed.": "Именно то, что нужно Барсику.",
  "Keep a word you’d like to practise again.": "Сохраните слово, которое хотите повторить.",
  "Keep these words fresh with flashcards, pictures and Russian audio.": "Повторяйте эти слова с карточками, картинками и русской озвучкой.",
  "Left": "Налево",
  "Left and right follow the way Barsik is facing.": "Лево и право определяются по направлению взгляда Барсика.",
  "Let’s play": "Начать игру",
  "Let’s take another look.": "Посмотрим ещё раз.",
  "Lingocoins": "Лингокоины",
  "Listen and rebuild the message": "Послушайте и соберите сообщение",
  "Listen at your own pace. You can pause, rewind or listen again.": "Слушайте в своём темпе. Можно остановить, перемотать и послушать ещё раз.",
  "Listen first. Replaying is welcome; reading the message is available when you need it.": "Сначала послушайте. Можно включить запись ещё раз или открыть текст.",
  "Listen in Russian": "Послушать по-русски",
  "Listen or reveal the text before checking.": "Перед проверкой послушайте запись или откройте текст.",
  "Listen to the Russian message and rebuild it with the word tiles. The English translation helps you follow its meaning.": "Послушайте русское сообщение и соберите его из слов. Английский перевод поможет понять смысл.",
  "Try Describe the scene": "Попробовать «Опиши сцену»",
  "Listen to the sentence": "Послушать предложение",
  "Listen to the complete message": "Послушать полное сообщение",
  "Listen to the message": "Послушать сообщение",
  "Listen to the message, then choose the picture it describes. You can replay it or reveal the Russian text if you need it.": "Послушайте сообщение и выберите подходящую картинку. Можно послушать снова или открыть русский текст.",
  "Listen to the programme first. The questions come next.": "Сначала послушайте передачу. Затем появятся вопросы.",
  "Listen to the radio programme": "Послушать радиопередачу",
  "Loading the programme…": "Загружаем передачу…",
  "Local installation": "Собственная установка",
  "Look at the picture and the route on each card. Both clues need to fit.": "Посмотрите на картинку и маршрут. Они должны соответствовать обеим подсказкам.",
  "Looking up": "Ищем",
  "Make another programme": "Создать другую передачу",
  "Market": "Рынок",
  "Match a picture": "Подобрать картинку",
  "Message": "Сообщение",
  "Message complete.": "Сообщение собрано.",
  "Message received.": "Сообщение получено.",
  "Messages to sort": "Сообщения для сортировки",
  "New": "Новое",
  "New game unlocked": "Открыта новая игра",
  "Next question": "Следующий вопрос",
  "Next round": "Следующий раунд",
  "On air": "В эфире",
  "One reply that fits": "Один из подходящих ответов",
  "Open dictionary": "Открыть словарь",
  "Opening flashcards…": "Открываем карточки…",
  "Opening questions…": "Открываем вопросы…",
  "Opening your games…": "Открываем игры…",
  "Opening your game…": "Открываем игру…",
  "Opening your saved game…": "Открываем сохранённую игру…",
  "Pack": "Положить",
  "Packed and ready.": "Всё собрано.",
  "Packed items": "Предметы в сумке",
  "Phrases for your reply": "Фразы для ответа",
  "Picture cards": "Карточки с картинками",
  "Plan the route": "Спланируйте маршрут",
  "Play": "Играть",
  "Play again": "Сыграть ещё раз",
  "Play with Barsik": "Играйте с Барсиком",
  "Possible deliveries": "Варианты доставки",
  "Post Office Radio": "Почтовое радио",
  "Post office": "Почта",
  "Practise familiar words and discover a few new ones along the way.": "Повторяйте знакомые слова и узнавайте новые.",
  "Practise missed items": "Повторить задания с ошибками",
  "Practise these words": "Повторить эти слова",
  "Preparation paused.": "Подготовка приостановлена.",
  "Preparation paused. You can retry from here.": "Подготовка приостановлена. Можно продолжить с этого места.",
  "Preparing the words and material for this game.": "Подготавливаем слова и материалы для игры.",
  "Programme transcript": "Текст передачи",
  "Put the tiles in the order you hear. Click a tile in your message to remove it.": "Расположите слова в том порядке, который слышите. Нажмите на слово в сообщении, чтобы убрать его.",
  "Question": "Вопрос",
  "Radio programme": "Радиопередача",
  "Read both clues, then choose the delivery card that fits them together. One clue on its own will not be enough.": "Прочитайте обе подсказки и выберите подходящую карточку доставки. Одной подсказки недостаточно.",
  "Read each Russian message and put it in the mailbox with its English meaning.": "Прочитайте русское сообщение и положите его в ящик с подходящим английским переводом.",
  "Read or listen to the Russian. Choose the pictures to put in Barsik’s bag, then check what you packed.": "Прочитайте или послушайте русский текст. Выберите картинки для сумки Барсика и проверьте результат.",
  "Read or listen to the Russian. Use the arrows to plan Barsik’s route, then check where he went.": "Прочитайте или послушайте русский текст. Спланируйте маршрут Барсика стрелками и проверьте его.",
  "Read or listen, then try the questions.": "Прочитайте или послушайте, затем ответьте на вопросы.",
  "Read the English translation and complete the Russian postcard. Choose the word that fits the whole sentence.": "Прочитайте английский перевод и дополните русскую открытку. Выберите слово, подходящее ко всему предложению.",
  "Ready to see what you caught?": "Проверим, что вы поняли?",
  "Ready to tune in": "Можно слушать",
  "Reload recording": "Загрузить запись снова",
  "Remove": "Убрать",
  "Reopen activities": "Открыть занятия",
  "Retry preparation": "Продолжить подготовку",
  "Review": "Повторение",
  "Right": "Направо",
  "Round": "Раунд",
  "Russian postcards": "Русские открытки",
  "Sample game": "Пример игры",
  "Saving…": "Сохраняем…",
  "Select a word to explore it or add it to your vocabulary.": "Выберите слово, чтобы узнать о нём больше или добавить в словарь.",
  "Selected lesson": "Выбранный урок",
  "Send the reply": "Отправить ответ",
  "Show a hint": "Показать подсказку",
  "Show the Russian text": "Показать русский текст",
  "Show transcript": "Показать текст",
  "Skip this item": "Пропустить задание",
  "Start a new game": "Начать новую игру",
  "Start over": "Начать заново",
  "Stop recording": "Остановить запись",
  "Straight": "Прямо",
  "Thanks for listening.": "Спасибо, что послушали.",
  "That reply does the job.": "Подходящий ответ.",
  "That’s right.": "Верно.",
  "That’s the message.": "Сообщение собрано верно.",
  "That’s the way.": "Верный маршрут.",
  "The dotted green line shows the route in the instructions.": "Зелёный пунктир показывает маршрут из задания.",
  "The mail is sorted.": "Почта рассортирована.",
  "The matching postcards": "Подходящие открытки",
  "The message": "Сообщение",
  "The postcard makes sense.": "Открытка заполнена верно.",
  "The programme could not load.": "Не удалось загрузить передачу.",
  "The programme could not load. Try loading it again.": "Не удалось загрузить передачу. Попробуйте ещё раз.",
  "The programme is being saved so you can replay it later.": "Передача сохраняется, чтобы её можно было послушать позже.",
  "The recorded message": "Сообщение из записи",
  "The recording could not play.": "Не удалось воспроизвести запись.",
  "The recording could not play. Try listening again.": "Не удалось воспроизвести запись. Попробуйте ещё раз.",
  "The recording could not play. Try loading it again.": "Не удалось воспроизвести запись. Попробуйте загрузить её снова.",
  "The recording is not ready yet. Try listening again.": "Запись ещё не готова. Попробуйте послушать позже.",
  "This game could not be found.": "Игра не найдена.",
  "This game is available in your own installation. Choose a sample from Activities to play here.": "Игра доступна в собственной установке. Здесь можно выбрать пример в разделе занятий.",
  "This game unlocks after": "Эта игра откроется после урока",
  "This is practice. Your first result is saved.": "Это повторение. Первый результат сохранён.",
  "This lesson has no saved words yet. Choose another word source.": "В этом уроке пока нет сохранённых слов. Выберите другой источник.",
  "This word could not be saved.": "Не удалось сохранить слово.",
  "This word could not load.": "Не удалось загрузить слово.",
  "Those pairs belong together.": "Пары составлены верно.",
  "Today’s programme": "Сегодняшняя передача",
  "Topic": "Тема",
  "Try a different match": "Попробуйте другую пару",
  "Try again": "Попробовать ещё раз",
  "Tune in": "Слушать",
  "Tune in to a short Russian radio programme, then answer four questions about what you heard.": "Послушайте короткую русскую радиопередачу, затем ответьте на четыре вопроса.",
  "Tuning in…": "Настраиваемся…",
  "Turn left": "Повернуть налево",
  "Turn right": "Повернуть направо",
  "Two clues. One delivery.": "Две подсказки. Одна доставка.",
  "Undo": "Отменить",
  "Use the full sentence and its translation to choose the missing word.": "Выберите пропущенное слово по предложению и его переводу.",
  "What Barsik needed": "Что было нужно Барсику",
  "What did you hear?": "Что вы услышали?",
  "Which word is used here?": "Какое слово используется здесь?",
  "Word source": "Источник слов",
  "Word tiles": "Слова для выбора",
  "Words for the missing space": "Варианты пропущенного слова",
  "Words for this game": "Слова для этой игры",
  "Words from this activity": "Слова из этого занятия",
  "Writing and recording today’s programme.": "Готовим и записываем сегодняшнюю передачу.",
  "You can find": "Вы найдёте",
  "You can undo a turn or start your route again before checking.": "До проверки можно отменить поворот или начать маршрут заново.",
  "You caught the message.": "Вы поняли сообщение.",
  "You followed the directions and helped Barsik on his way.": "Вы следовали указаниям и помогли Барсику в пути.",
  "You found the way.": "Вы нашли дорогу.",
  "You used your Russian to help Barsik pack his bag.": "Вы использовали русский язык, чтобы помочь Барсику собрать сумку.",
  "Your": "Ваше",
  "Your answer": "Ваш ответ",
  "Your flashcards could not open. Please try again.": "Не удалось открыть карточки. Попробуйте ещё раз.",
  "Your game could not be saved.": "Не удалось сохранить игру.",
  "Your game is saved. You’ve earned today’s activity coins, and you can keep playing.": "Игра сохранена. Монеты за занятия сегодня уже получены. Можно продолжать играть.",
  "Your games could not load.": "Не удалось загрузить игры.",
  "Your moves will appear here.": "Здесь появятся ваши ходы.",
  "Your planned route": "Ваш маршрут",
  "Your postcards are complete.": "Открытки заполнены.",
  "Your practice is saved on this device.": "Результат сохранён на этом устройстве.",
  "Your practice is saved. No extra coins were added this time.": "Результат сохранён. В этот раз дополнительные монеты не начислены.",
  "Your profile changed. Reopen this page before continuing.": "Профиль изменился. Откройте страницу заново.",
  "Your progress is saved as the game is prepared.": "Ход подготовки игры сохраняется.",
  "Your unlocked games": "Ваши открытые игры",
  "You’re practising with the written message this time.": "В этот раз вы занимаетесь с письменным текстом.",
  "You’ve already earned coins for this game today. You can keep playing.": "Сегодня вы уже получили монеты за эту игру. Можно продолжать играть.",
  "You’ve listened to a Russian programme and checked what you understood.": "Вы послушали русскую передачу и проверили, что поняли.",
  "You’ve played all": "Вы прошли все",
  "You’ve practised choosing Russian words in their sentences.": "Вы потренировались выбирать русские слова в предложениях.",
  "You’ve practised hearing how Russian words fit together in a sentence.": "Вы потренировались слышать, как русские слова складываются в предложение.",
  "You’ve practised recognising your Russian words in pictures.": "Вы потренировались узнавать русские слова по картинкам.",
  "You’ve practised understanding Russian in context.": "Вы потренировались понимать русский язык в контексте.",
  "You’ve practised understanding Russian messages in context.": "Вы потренировались понимать русские сообщения в контексте.",
  "You’ve practised using two Russian clues together to find a delivery.": "Вы использовали две русские подсказки, чтобы найти нужную доставку.",
  "correct on the first try.": "верно с первой попытки.",
  "these games": "эти игры",
  "this game": "эту игру",
  "to build this game.": "для этой игры.",
  "to put it in the bag.": "и положите её в сумку.",
  "to unlock.": "чтобы открыть игру.",
  "whenever you want to play again.": "когда захотите сыграть снова.",
  "your vocabulary": "ваш словарь",
  ". Each arrow moves him one street.": ". Каждая стрелка перемещает его на одну улицу.",
  "up": "вверх",
  "down": "вниз",
  "left": "налево",
  "right": "направо",
  "words": "слов",
  "of": "из",
  "ready": "готово",
  "rounds.": "раундов.",
  "game": "игра",
  "games": "игр",
  "in": "в",
  "message": "сообщение",
  "reply": "ответ",
  "Pack the bag": "Собери сумку",
  "Follow the directions": "Следуй указаниям",
  "Postcard Pairs": "Пары открыток",
  "Missing Stamp": "Пропущенное слово",
  "Mailbox Sort": "Сортировка почты",
  "A Letter Back": "Ответное письмо",
  "Lost Parcel Detective": "Поиск посылки",
  "What’s in the bag?": "Что в сумке?",
  "Which way?": "Куда идти?",
  "Ask for help": "Попроси о помощи",
  "Ready to set off": "Можно отправляться",
  "Match the Russian messages to picture cards for Barsik’s bag.": "Подберите картинки к русским сообщениям для сумки Барсика.",
  "Follow Russian directions to guide Barsik through the streets.": "Проведите Барсика по улицам, следуя русским указаниям.",
  "Match the Russian on each postcard to its picture.": "Подберите картинку к русскому тексту на открытке.",
  "Put the missing Russian word back into each message.": "Вставьте пропущенное русское слово в каждое сообщение.",
  "Listen to a short Russian radio programme, then answer four questions.": "Послушайте короткую русскую радиопередачу и ответьте на четыре вопроса.",
  "Match Russian messages to their English meanings.": "Подберите английский перевод к каждому русскому сообщению.",
  "Listen to a message and rebuild it with word tiles.": "Послушайте сообщение и соберите его из слов.",
  "Use both clues to find the right delivery card.": "Найдите нужную карточку доставки по двум подсказкам.",
  "Follow the Russian directions to guide Barsik.": "Проведите Барсика по маршруту, следуя русским указаниям.",
  "Show Barsik which way to go.": "Покажите Барсику, куда идти.",
  "Put these things in Barsik’s bag.": "Положите эти вещи в сумку Барсика.",
  "Pack the picture cards that match the messages.": "Положите в сумку картинки, которые подходят к сообщениям.",
  "Match the Russian messages to their pictures.": "Подберите картинки к русским сообщениям.",
  "Match each Russian postcard to its picture.": "Подберите картинку к каждой русской открытке.",
  "Complete the Russian message using its English translation.": "Дополните русское сообщение по английскому переводу.",
  "Put the missing word back into the message.": "Вставьте пропущенное слово в сообщение.",
  "Sort the messages by their English meaning.": "Рассортируйте сообщения по английскому переводу.",
  "Put each message in the right mailbox.": "Положите каждое сообщение в нужный ящик.",
  "Listen, then rebuild the message in the order you heard it.": "Послушайте и соберите сообщение в том же порядке.",
  "Find the picture and route that match both clues.": "Найдите картинку и маршрут по двум подсказкам.",
  "Read the whole English sentence, then choose the Russian form that fits.": "Прочитайте всё английское предложение и выберите подходящую русскую форму.",
  "Vocabulary bands describe the words, not a TORFL level.": "Сложность слов не определяет уровень ТРКИ.",
  "5 rounds": "5 раундов",
  "10 rounds": "10 раундов",
  " · easiest": " · самые простые",
  "Sentence meaning": "Значение предложения",
  "Word form": "Форма слова"
};

Object.assign(gameRussian, {
  "Take {0} out of the bag": "Убрать из сумки: {0}",
  "Needed in the bag: {0}": "Нужно в сумке: {0}",
  "Not needed: {0}": "Не нужно: {0}",
  "Street map. Barsik is at column {0}, row {1}, facing {2}. {3} of {4} moves planned.": "Карта улиц. Барсик в столбце {0}, строке {1}, смотрит {2}. Запланировано ходов: {3} из {4}.",
  "Listen: {0}": "Послушать: {0}",
  "Stop recording: {0}": "Остановить запись: {0}",
  "Listen to phrase {0}": "Послушать фразу {0}",
  "Listen to message {0}": "Послушать сообщение {0}",
  "Listen to part {0}": "Послушать часть {0}",
  "Paired with postcard {0}": "В паре с открыткой {0}",
  "Picture of {0}": "Картинка: {0}",
  "Match with {0}": "Составить пару: {0}",
  "Put the message in {0}": "Положить сообщение в ящик: {0}",
  "{0} messages": "Сообщения: {0}",
  "Your Russian {0}": "Ваш текст на русском",
  "Remove {0} from your {1}": "Убрать: {0}",
  "Word: {0}": "Слово: {0}",
  "{0} rounds.": "Раундов: {0}"
});

Object.assign(gameRussian, {
  'Choose words for flashcards': 'Выбрать слова для карточек',
  'Keep the words you want to practise.': 'Выберите слова, которые хотите повторить.',
});

Object.assign(gameRussian, {
 'One letter · Three connected stops':'Одно письмо · Три связанные остановки',
 'This is a saved route from the earlier game.':'Это сохранённый маршрут из предыдущей игры.',
 'Start a neighbourhood delivery':'Начать доставку по району',
 'Explore a neighbourhood, ask the people you meet for directions and deliver a letter.':'Исследуй район, спрашивай дорогу у встречных и доставь письмо.',
});

Object.assign(gameRussian, {
  'Build the sentence to describe the scene.': 'Составьте предложение, чтобы описать сцену.',
  'Build Russian sentences about position, movement and who does what.': 'Составляйте предложения по-русски о положении предметов, движении и действиях людей.',
  'Describe the scene': 'Опишите сцену',
  'Look at the scene and build the Russian sentence. Choose the words and endings that fit.': 'Посмотрите на сцену и составьте предложение по-русски. Выберите подходящие слова и окончания.',
  'Check the sentence': 'Проверить предложение',
  'Choose an answer in each row. You can change it before checking.': 'Выберите ответ в каждой строке. До проверки его можно изменить.',
  'Practice complete.': 'Практика завершена.',
  'You’ve practised how Russian describes places, actions and people.': 'Вы потренировались описывать места, действия и людей по-русски.',
  'That fits the scene.': 'Это подходит к сцене.',
  'Complete the Russian sentence to describe the scene.': 'Дополните предложение по-русски, чтобы описать сцену.',
});

Object.assign(gameRussian, {
  'Choose an activity': 'Выбрать занятие',
  'Opens after earning {0} Lingocoins in activities.': 'Откроется, когда вы заработаете {0} лингокоинов за практику.',
  '{0} / {1} earned': 'Заработано: {0} из {1}',
  '{0} / {1} Lingocoins earned': 'Заработано лингокоинов: {0} из {1}',
  'Earn Lingocoins from your main activities to open this game.': 'Зарабатывайте лингокоины в основных занятиях, чтобы открыть эту игру.',
  'Earn Lingocoins from reading, writing, speaking and other activities to open new games.': 'Зарабатывайте лингокоины за чтение, письмо, разговорную практику и другие занятия, чтобы открывать новые игры.',
  'Introductory rewards, game rewards and brought-forward coins do not count towards game unlocks.': 'Монеты за вводные уроки, награды за игры и перенесённые монеты не учитываются при открытии новых игр.',
});
